// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaCaGR7kL6GeEqCY9rXGKvhUTezb4rFMo',
    appId: '1:803074704695:web:b1ffe3439cbf36d75546b2',
    messagingSenderId: '803074704695',
    projectId: 'future-advanced',
    authDomain: 'future-advanced.firebaseapp.com',
    storageBucket: 'future-advanced.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQnCqwVBwoDQV2YOJO-IzOgU416wE-8jY',
    appId: '1:803074704695:android:7988ef394fca09bd5546b2',
    messagingSenderId: '803074704695',
    projectId: 'future-advanced',
    storageBucket: 'future-advanced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZXnTiBIIafCIyu7IMLLZkH1bpcpgmns',
    appId: '1:803074704695:ios:c2094378d68ccc935546b2',
    messagingSenderId: '803074704695',
    projectId: 'future-advanced',
    storageBucket: 'future-advanced.appspot.com',
    iosClientId: '803074704695-v0p2ji34fpktv3hcuglegkdac1p4k143.apps.googleusercontent.com',
    iosBundleId: 'com.example.apptesttest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZXnTiBIIafCIyu7IMLLZkH1bpcpgmns',
    appId: '1:803074704695:ios:c2094378d68ccc935546b2',
    messagingSenderId: '803074704695',
    projectId: 'future-advanced',
    storageBucket: 'future-advanced.appspot.com',
    iosClientId: '803074704695-v0p2ji34fpktv3hcuglegkdac1p4k143.apps.googleusercontent.com',
    iosBundleId: 'com.example.apptesttest',
  );
}
